TRUNCATE TABLE  paragrafo;
TRUNCATE TABLE  paragrafo_argomento;
TRUNCATE TABLE  paragrafo_subargomento;
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (1,'PREFILATELICHE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (2,'ANTICHI STATI',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (3,'ITALIA REGNO',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (4,'REPUBBLICA SOCIALE ITALIANA',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (5,'LUOGOTENENZA',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (6,'EMISSIONI LOCALI',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (7,'COLONIE ITALIANE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (8,'OCCUPAZIONI STRANIERE - I GUERRA MONDIALE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (9,'TERRE REDENTE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (10,'OCCUPAZIONI ITALIANE - II GUERRA MONDIALE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (11,'LEVANTE ITALIANO',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (12,'OCCUPAZIONI STRANIERE - II GUERRA MONDIALE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (13,'REPUBBLICA',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (15,'TRIESTE A',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (16,'SAN MARINO',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (17,'VATICANO',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (18,'EUROPA',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (19,'OLTREMARE',1);
INSERT INTO  paragrafo ( idparagrafo ,descrizione ,stato) VALUES (20,'LOTTI E COLLEZIONI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (1,1,'PREFILATELICHE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (2,2,'LOMBARDO VENETO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (3,2,'MODENA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (4,2,'NAPOLI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (5,2,'PARMA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (6,2,'PONTIFICIO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (7,2,'ROMAGNE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (8,2,'SARDEGNA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (9,2,'SICILIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (10,2,'TOSCANA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (11,3,'ITALIA REGNO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (12,3,'POSTA AEREA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (13,3,'SERVIZIO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (14,3,'ESPRESSI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (15,3,'POSTA PNEUMATICA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (16,3,'PACCHI POSTALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (17,3,'SEGNATASSE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (18,3,'SERVIZIO COMMISSIONI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (19,3,'BLP',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (20,3,'PUBBLICITARI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (21,3,'ENTI PARASTATALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (22,4,'REPUBBLICA SOCIALE ITALIANA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (23,4,'RSI - PROVE E VARIETA''',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (24,5,'LUOGOTENENZA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (25,6,'EMISSIONI LOCALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (26,6,'EMISSIONI AUTORIZZATE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (27,6,'CLN',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (28,6,'CORPO POLACCO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (29,7,'GIRI COLONIALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (30,7,'EMISSIONI GENERALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (31,7,'AOI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (32,7,'CASTELROSSO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (33,7,'CIRENAICA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (34,7,'EGEO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (35,7,'EGEO - ISOLE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (36,7,'ERITREA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (37,7,'LIBIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (38,7,'OLTRE GIUBA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (39,7,'SASENO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (40,7,'SOMALIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (41,7,'TRIPOLITANIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (42,8,'OCCUPAZIONI STRANIERE - I GUERRA MONDIALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (43,9,'TERRE REDENTE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (44,10,'OCCUPAZIONI ITALIANE - II GUERRA MONDIALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (45,11,'LEVANTE ITALIANO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (46,12,'OCCUPAZIONI STRANIERE - II GUERRA MONDIALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (47,14,'REPUBBLICA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (48,15,'TRIESTE A',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (49,16,'SAN MARINO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (50,17,'VATICANO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (51,18,'BELGIO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (52,18,'FRANCIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (53,18,'GERMANIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (54,18,'ANTICHI STATI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (55,18,'IMPERO REICH',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (56,18,'GERMANIA OCCIDENTALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (57,18,'GERMANIA ORIENTALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (58,18,'GERMANIA BERLINO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (59,18,'GERMANIA OCCUPAZIONI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (60,18,'SARRE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (61,18,'EMISSIONI LOCALI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (62,18,'GERM. OCCUP. - II GUERRA MONDIALE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (63,18,'GRAN BRETAGNA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (64,18,'SVIZZERA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (65,19,'ISRAELE',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (66,20,'PREFILATELIA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (67,20,'ANTICHI STATI',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (68,20,'REGNO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (69,20,'REPUBBLICA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (70,20,'TRIESTE A',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (71,20,'REPUBBLICA DI SAN MARINO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (72,20,'VATICANO',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (73,20,'EUROPA',1);
INSERT INTO paragrafo_argomento (idargomento, idparagrafo, descrizione, stato) VALUES (74,19,'OLTREMARE',1);
INSERT INTO  paragrafo_subargomento (idsub_argomento ,idargomento ,descrizione ,stato)VALUES ('1',  '25',  'GERMANIA',  '1');
